# Generated by Django 6.0 on 2025-12-29 12:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patron_id', models.CharField(help_text='Student or Faculty ID', max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty')], max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('program', models.CharField(blank=True, max_length=100, null=True)),
                ('year_level', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_only', models.DateField(auto_now_add=True, db_index=True)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='library_app.patron')),
            ],
            options={
                'ordering': ['-scan_time'],
            },
        ),
    ]
