# Generated by Django 6.0 on 2025-12-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patron',
            old_name='patron_id',
            new_name='id_number',
        ),
        migrations.AlterField(
            model_name='patron',
            name='department',
            field=models.CharField(choices=[('SBS', 'School of Business and Sciences (SBS)'), ('SEAS', 'School of Education, Arts, and Sciences (SEAS)'), ('SHES', 'School of Health and Education Sciences (SHES)'), ('BES', 'Basic Education School (BES)'), ('MAS', 'Multimedia Arts and Sciences (MAS)')], max_length=100),
        ),
    ]
