# Generated by Django 6.0 on 2025-12-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_rename_patron_id_patron_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
