# Generated by Django 6.0 on 2025-12-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_attendancelog_time_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='department',
            field=models.CharField(choices=[('SBS', 'School of Business Sciences (SBS)'), ('SEAS', 'School of Education, Arts, and Sciences (SEAS)'), ('SHES', 'School of Health and Education Sciences (SHES)'), ('BES', 'Basic Education School (BES)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='patron',
            name='id_number',
            field=models.CharField(help_text='Numeric ID only', max_length=50, unique=True),
        ),
    ]
