# Generated by Django 6.0 on 2025-12-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_alter_patron_department_alter_patron_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
