# Generated by Django 6.0 on 2026-01-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_patron_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='department',
            field=models.CharField(blank=True, choices=[('SBS', 'School of Business Sciences (SBS)'), ('SEAS', 'School of Education, Arts, and Sciences (SEAS)'), ('SHES', 'School of Health and Education Sciences (SHES)'), ('BES', 'Basic Education School (BES)')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patron',
            name='id_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='patron',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('guest', 'Guest')], default='student', max_length=10),
        ),
    ]
