# Generated by Django 6.0 on 2026-01-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_alter_patron_department_alter_patron_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patron',
            name='department',
            field=models.CharField(blank=True, choices=[('SBS', 'School of Business Sciences (SBS)'), ('SEAS', 'School of Education, Arts, and Sciences (SEAS)'), ('SHES', 'School of Health and Education Sciences (SHES)'), ('BES', 'Basic Education School (BES)'), ('GS', 'Graduate School')], max_length=100, null=True),
        ),
    ]
