# Generated by Django 6.0 on 2026-01-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_patron_major_alter_patron_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
