# Generated by Django 6.0 on 2026-01-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_patron_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='year_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
